//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryDataEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bakeries_networkEntities : DbContext
    {
        public bakeries_networkEntities()
            : base("name=bakeries_networkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bakery> bakery { get; set; }
        public DbSet<categories> categories { get; set; }
        public DbSet<employee> employee { get; set; }
        public DbSet<holders> holders { get; set; }
        public DbSet<positions> positions { get; set; }
        public DbSet<product> product { get; set; }
    }
}
