//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class bakery
    {
        public bakery()
        {
            this.employee = new HashSet<employee>();
        }
    
        public int BK_ID { get; set; }
        public string BK_CITY { get; set; }
        public string BK_ADRS { get; set; }
        public Nullable<int> BK_HOLDER { get; set; }
    
        public virtual holders holders { get; set; }
        public virtual ICollection<employee> employee { get; set; }
    }
}
