//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class positions
    {
        public positions()
        {
            this.employee = new HashSet<employee>();
        }
    
        public int POS_ID { get; set; }
        public string POS_NAME { get; set; }
    
        public virtual ICollection<employee> employee { get; set; }
    }
}
