//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int PR_ID { get; set; }
        public string PR_NAME { get; set; }
        public Nullable<decimal> PR_COST { get; set; }
        public Nullable<int> PR_CAT { get; set; }
    
        public virtual categories categories { get; set; }
    }
}
